### ISSUE TITLE
Please Update for Minecraft v1.20.6

### ISSUE THREAD

**Issue by leefy-greens** [SlimeDog/AggressiveAnimals#104]
**Is your feature request related to a problem? Please describe.**
Current version supports stops at 1.20.4

**Describe the solution you'd like**
Support for 1.20.6

**Describe alternatives you've considered**
looking for another similar plugin

**Additional context**
n/a

**Comment by SlimeDog** [comment]
Pending...

**Comment by SlimeDog** [comment]
Update posted to Hangar and SpigotMC.
