### ISSUE TITLE
Cant Kill player low life

### ISSUE THREAD

**Issue by Frithy0** [SlimeDog/AggressiveAnimals#2]
**Description**
The animals cant kill a player if he has 0.5 heart

**Reproduction steps**
Config : 
[config.yml.txt](https://github.com/SlimeDog/AggressiveAnimals/files/8997704/config.yml.txt)

To have 0.5 heart 

**Screenshots**
![image](https://user-images.githubusercontent.com/56309938/176092453-f4b20e04-6b99-4241-b022-470faf154302.png)

**Server Environment**
 - OS [Linux, MacOS, Windows] version: Windows 10
- Java version [java -version]:  18.0.1.1
 - Server version [/version]: PurPur-1684 (MC:1.19)
 - AggressiveAnimals version [/version AggressiveAnimals]: 1.1.0

**Comment by SlimeDog** [comment]
Please share your config.yml

**Comment by SlimeDog** [comment]
Your config.yml, like the default, includes
```
  attack-damage-limit: 2.0         # The attacker will leave the target alive with the specified amount of health (in half hearts)
```
Set it to
```
  attack-damage-limit: 0.0         # The attacker will leave the target alive with the specified amount of health (in half hearts)
```
to allow mobs to kill players.

**Comment by Frithy0** [comment]
Hooo ok thx
