### ISSUE TITLE
mobs attack players on their team

### ISSUE THREAD

**Issue by 11Den11xz00** [SlimeDog/AggressiveAnimals#50]
version 1.19.2 
AggressiveAnimals 1.4.2
[config.zip](https://github.com/SlimeDog/AggressiveAnimals/files/11969508/config.zip)

vanilla mobs (snow man)

By making  snowman aggressive with your plugin. I made a team using the standard command /team by adding myself and the mob to the same team. But after appearing, the snowman starts attacking me. Which shouldn't have been.

**Comment by SlimeDog** [comment]
Thanks for the details. We'll have a look at it.

**Comment by SlimeDog** [comment]
Included in AA 1.5.0
