### ISSUE TITLE
Name for mobs

### ISSUE THREAD

**Issue by vtuong1998** [SlimeDog/AggressiveAnimals#58]
when I name the mob it won't attack me anymore?How to fix?

**Comment by SlimeDog** [comment]
Please see [Wiki: How It Works](https://github.com/SlimeDog/AggressiveAnimals/wiki/How-It-Works) and [Wiki: Configuration](https://github.com/SlimeDog/AggressiveAnimals/wiki/Configuration)

Both point to the configuration file `config.yml`, which is liberally commented, including the answer to this question:
```
...
defaults:
...
  include-named-mobs: false        # If true, include named mobs
...
```
So set   `include-named-mobs: true` and then execute the command `aggro reload`
